/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view.dialog;

import javax.swing.JFrame;

/**
 *
 * @author gutei
 */
public class DlgSecretaria extends javax.swing.JDialog {

    /**
     * Creates new form DlgSecretaria
     */
    public DlgSecretaria(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlFundo = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        btnCadastroProcedimento = new javax.swing.JButton();
        btnCadastrarPaciente = new javax.swing.JButton();
        btnVisualizarHistorico = new javax.swing.JButton();
        btnCadastrarConsulta = new javax.swing.JButton();
        btnVisualizarAgenda = new javax.swing.JButton();
        btnRelatorioProcedimentos = new javax.swing.JButton();
        btnReceberFeedback = new javax.swing.JButton();
        btnReceberPagamento = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pnlFundo.setBackground(new java.awt.Color(255, 228, 228));
        pnlFundo.setForeground(new java.awt.Color(255, 228, 228));

        lblLogo.setFont(new java.awt.Font("Monotype Corsiva", 0, 14)); // NOI18N
        lblLogo.setForeground(new java.awt.Color(255, 121, 165));
        lblLogo.setText("BellaTech  ©2023");

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 121, 165));
        lblTitulo.setText("SELECIONE UMA AÇÃO PARA PROSSEGUIR");

        btnCadastroProcedimento.setBackground(new java.awt.Color(255, 121, 165));
        btnCadastroProcedimento.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCadastroProcedimento.setForeground(new java.awt.Color(255, 255, 255));
        btnCadastroProcedimento.setText("CADASTRAR PROCEDIMENTO");
        btnCadastroProcedimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastroProcedimentoActionPerformed(evt);
            }
        });

        btnCadastrarPaciente.setBackground(new java.awt.Color(255, 121, 165));
        btnCadastrarPaciente.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCadastrarPaciente.setForeground(new java.awt.Color(255, 255, 255));
        btnCadastrarPaciente.setText("CADASTRAR PACIENTE");
        btnCadastrarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarPacienteActionPerformed(evt);
            }
        });

        btnVisualizarHistorico.setBackground(new java.awt.Color(255, 121, 165));
        btnVisualizarHistorico.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnVisualizarHistorico.setForeground(new java.awt.Color(255, 255, 255));
        btnVisualizarHistorico.setText("VISUALIZAR HISTÓRICO DE PROCEDIMENTOS");
        btnVisualizarHistorico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisualizarHistoricoActionPerformed(evt);
            }
        });

        btnCadastrarConsulta.setBackground(new java.awt.Color(255, 121, 165));
        btnCadastrarConsulta.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCadastrarConsulta.setForeground(new java.awt.Color(255, 255, 255));
        btnCadastrarConsulta.setText("CADASTRAR CONSULTA");
        btnCadastrarConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarConsultaActionPerformed(evt);
            }
        });

        btnVisualizarAgenda.setBackground(new java.awt.Color(255, 121, 165));
        btnVisualizarAgenda.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnVisualizarAgenda.setForeground(new java.awt.Color(255, 255, 255));
        btnVisualizarAgenda.setText("VISUALIZAR AGENDA DE CONSULTAS");
        btnVisualizarAgenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisualizarAgendaActionPerformed(evt);
            }
        });

        btnRelatorioProcedimentos.setBackground(new java.awt.Color(255, 121, 165));
        btnRelatorioProcedimentos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnRelatorioProcedimentos.setForeground(new java.awt.Color(255, 255, 255));
        btnRelatorioProcedimentos.setText("FAZER RELATÓRIO DE PROCEDIMENTOS");
        btnRelatorioProcedimentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRelatorioProcedimentosActionPerformed(evt);
            }
        });

        btnReceberFeedback.setBackground(new java.awt.Color(255, 121, 165));
        btnReceberFeedback.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnReceberFeedback.setForeground(new java.awt.Color(255, 255, 255));
        btnReceberFeedback.setText("RECEBER FEEDBACK DOS PACIENTES");
        btnReceberFeedback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReceberFeedbackActionPerformed(evt);
            }
        });

        btnReceberPagamento.setBackground(new java.awt.Color(255, 121, 165));
        btnReceberPagamento.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnReceberPagamento.setForeground(new java.awt.Color(255, 255, 255));
        btnReceberPagamento.setText("RECEBER PAGAMENTO DO PACIENTE");
        btnReceberPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReceberPagamentoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlFundoLayout = new javax.swing.GroupLayout(pnlFundo);
        pnlFundo.setLayout(pnlFundoLayout);
        pnlFundoLayout.setHorizontalGroup(
            pnlFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFundoLayout.createSequentialGroup()
                .addGroup(pnlFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlFundoLayout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlFundoLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(pnlFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTitulo)
                            .addGroup(pnlFundoLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(pnlFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(btnCadastrarPaciente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnVisualizarHistorico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnCadastrarConsulta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnVisualizarAgenda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnRelatorioProcedimentos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnCadastroProcedimento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnReceberFeedback, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnReceberPagamento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        pnlFundoLayout.setVerticalGroup(
            pnlFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFundoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCadastroProcedimento, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCadastrarPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnVisualizarHistorico, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCadastrarConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnVisualizarAgenda, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnRelatorioProcedimentos, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnReceberFeedback, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnReceberPagamento, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(lblLogo)
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFundo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFundo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarPacienteActionPerformed
        DlgCadastroPaciente telaCadastroPaciente = new DlgCadastroPaciente(new JFrame(), true);
        telaCadastroPaciente.setVisible(true);
    }//GEN-LAST:event_btnCadastrarPacienteActionPerformed

    private void btnVisualizarAgendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisualizarAgendaActionPerformed
        DlgVisualizarAgendaDeConsultas telaAgendaConsultas = new DlgVisualizarAgendaDeConsultas(new JFrame(), true);
        telaAgendaConsultas.setVisible(true); 
    }//GEN-LAST:event_btnVisualizarAgendaActionPerformed

    private void btnRelatorioProcedimentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRelatorioProcedimentosActionPerformed
        DlgRelatorioProcedimento telaRelatorioProcedimento = new DlgRelatorioProcedimento(new JFrame(), true);
        telaRelatorioProcedimento.setVisible(true);
    }//GEN-LAST:event_btnRelatorioProcedimentosActionPerformed

    private void btnCadastroProcedimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastroProcedimentoActionPerformed
        DlgCadastroProcedimento telaCadastroProcedimento = new DlgCadastroProcedimento(new JFrame(), true);
        telaCadastroProcedimento.setVisible(true);
    }//GEN-LAST:event_btnCadastroProcedimentoActionPerformed

    private void btnVisualizarHistoricoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisualizarHistoricoActionPerformed
        DlgHistoricoProcedimentos telaHistoricoProcedimentos = new DlgHistoricoProcedimentos(new JFrame(), true);
        telaHistoricoProcedimentos.setVisible(true);
    }//GEN-LAST:event_btnVisualizarHistoricoActionPerformed

    private void btnCadastrarConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarConsultaActionPerformed
        DlgCadastrarConsulta telaCadastroConsulta = new DlgCadastrarConsulta(new JFrame(), true);
        telaCadastroConsulta.setVisible(true);
    }//GEN-LAST:event_btnCadastrarConsultaActionPerformed

    private void btnReceberFeedbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReceberFeedbackActionPerformed
        DlgReceberFeedback telaFeedback = new DlgReceberFeedback(new JFrame(), true);
        telaFeedback.setVisible(true);

    }//GEN-LAST:event_btnReceberFeedbackActionPerformed

    private void btnReceberPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReceberPagamentoActionPerformed
        DlgReceberPagamento telaPagamento = new DlgReceberPagamento(new JFrame(), true);
        telaPagamento.setVisible(true);

    }//GEN-LAST:event_btnReceberPagamentoActionPerformed

 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrarConsulta;
    private javax.swing.JButton btnCadastrarPaciente;
    private javax.swing.JButton btnCadastroProcedimento;
    private javax.swing.JButton btnReceberFeedback;
    private javax.swing.JButton btnReceberPagamento;
    private javax.swing.JButton btnRelatorioProcedimentos;
    private javax.swing.JButton btnVisualizarAgenda;
    private javax.swing.JButton btnVisualizarHistorico;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel pnlFundo;
    // End of variables declaration//GEN-END:variables
}
